@startuml Authorization-Enhanced Internet Mail Architecture, message flow part I.

/'
Message
Message User Agent (MUA)
    Author MUA (aMUA)
    Recipient MUA (rMUA)
Message Submission Agent (MSA)
    Author-focused MSA functions (aMSA)
    MHS-focused MSA functions (hMSA)
Message Transfer Agent (MTA)
Message Delivery Agent (MDA)
    Recipient-focused MDA functions (rMDA)
    MHS-focused MDA functions (hMDA)
Resource Fetch Agent (RFA)
Resource Access Agent (RAA)
Mail Resource Store (MRS)
    Author MRS (aMRS)
    Recipient MRS (rMRS)    
    User Agent MRS (uMRS)
'/

'ADMD I.
participant "aMUA" as aMUA /'MUA, uMRS optional'/
box "RAA" /'Resource Access Agent'/
participant "aMRS" as aMRS /'Author MRS'/
end box
box "MSA" /'MSA'/
participant "aMSA" as aMSA /'Author-focused MSA'/
participant "hMSA" as hMSA /'MHS-focused MSA'/
end box
participant "MTA" as MTA /'MTA'/

aMUA -> aMRS : 1 Mail resources archiving/sync (local, imap, http)
aMUA -> aMSA : 2.1 Placeholder message submission (smtp)
aMSA -> hMSA : 2.2 Posting (S) transition
hMSA -> MTA : 3.1 Placeholder message transfer (smtp)
MTA ->] : 3.2 Placeholder message transfer (smtp)
aMRS <-] : a) Fetch (sync) mail resources request (http), using the Internet Mail Federation Protocol
aMRS -->] : b) Fetch (sync) mail resources response (http)

@enduml

