@startuml Authorization-Enhanced Mail Architecture
title Authorization-Enhanced Internet Mail Architecture (AEIMA)

/'
Message
Message User Agent (MUA)
    Author MUA (aMUA)
    Recipient MUA (rMUA)
Message Submission Agent (MSA)
    Author-focused MSA functions (aMSA)
    MHS-focused MSA functions (hMSA)
Message Transfer Agent (MTA)
Message Delivery Agent (MDA)
    Recipient-focused MDA functions (rMDA)
    MHS-focused MDA functions (hMDA)
Mail Resource Store (MRS)
    Author MRS (aMRS)
    Recipient MRS (rMRS)
Resource Fetch Agent (RFA)
    Author RFA (aRFA)
    Recipient RFA (rRFA)    
Resource Handling Agent (RHA)
    Author RHA (aRHA)
    Recipient RHA (rRHA)
'/

'ADMD foo
box "ADMD foo"
participant "aMUA" as aMUAfoo /'MUA (ADMD foo)'/
participant "aRHA" as aRHAfoo /'Author RHA (ADMD foo)'/
participant "aMRS" as aMRSfoo /'Author MRS (ADMD foo)'/
participant "aMSA" as aMSAfoo /'Author-focused MSA (ADMD foo)'/
participant "hMSA" as hMSAfoo /'MHS-focused MSA (ADMD foo)'/
participant "MTA" as MTAfoo /'MTA (ADMD foo)'/
end box

'ADMD bar
box "ADMD bar"
participant "MTA" as MTAbar /'MTA (ADMD bar)'/
participant "hMDA" as hMDAbar /'MHS-focused MDA (ADMD bar)'/
participant "rMDA" as rMDAbar /'Recipient-focused MDA (ADMD bar)'/
participant "rRFA" as rRFAbar /'Recipient RFA (ADMD bar)'/
participant "rMRS" as rMRSbar /'Recipient MRS (ADMD bar)'/
participant "rRHA" as rRHAbar /'Recipient RHA (ADMD bar)'/
participant "rMUA" as rMUAbar /'MUA (ADMD bar)'/
end box
@enduml

