@startuml Internet Mail Architecture (rfc5598), message flow part II.

/'
Message
Message User Agent (MUA)
    Author MUA (aMUA)
    Recipient MUA (rMUA)
Message Submission Agent (MSA)
    Author-focused MSA functions (aMSA)
    MHS-focused MSA functions (hMSA)
Message Transfer Agent (MTA)
Message Delivery Agent (MDA)
    Recipient-focused MDA functions (rMDA)
    MHS-focused MDA functions (hMDA)
Message Store (MS)
    Author MS (aMS)
    Recipient MS (rMS)
    User Agent MS (uMS)
'/

'ADMD II.
participant "MTA" as MTA /'MTA'/
box "MDA"
participant "hMDA" as hMDA /'MHS-focused MDA'/
participant "rMDA" as rMDA /'Recipient-focused MDA'/
end box
participant "rMS" as rMS /'Recipient MS'/
participant "rMUA" as rMUA /'MUA, uMS optional'/

[-> MTA : 3.2 Message transfer (smtp)
MTA -> hMDA : 3.3 Message transfer (local, smtp, lmtp)
hMDA -> rMDA : 4.1 Delivery (D) transition
rMDA -> rMS : 4.2 Message delivery (local, smtp)
rMS -> rMUA : 5 Message retrieval/sync (local, pop, imap)

@enduml

